include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops.yml
    ref: v21.0.2

variables:
  AUTO_DEVOPS_KANIKO: "🕹️"
  AUTO_DEVOPS_ENABLE_KAPP: "🕹️"
  AUTO_DEVOPS_RELEASE_AUTO: "🔖"
  AUTO_DEVOPS_PRODUCTION_AUTO: "🚀"

# NOTE(douglasduteil): No install :(
# sharing the node_modules is too slow...
Install:
  rules:
    - when: never

Lint:
  rules:
    - when: never

Test:
  rules:
    - when: never

Production:
  extends: .autodevops_production
  variables:
    KOSKO_APPEND_YAML_FROM: .socialgouv/environments/prod/manifests

Build:
  needs: []
  cache:
    key:
      files:
        - yarn.lock
      prefix: ${CI_JOB_NAME}
    paths:
      - .cache
  script:
    - yarn config set cache-folder $CI_PROJECT_DIR/.cache/yarn
    - yarn --frozen-lockfile --prefer-offline
    - yarn build
    - yarn export
  variables:
    VERSION: ${CI_COMMIT_SHORT_SHA}
  artifacts:
    expire_in: 1 day
    paths:
      - out
