name: Production

on:
  push:
    tags:
      - v*

concurrency:
  group: production
  cancel-in-progress: true

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://ozensemble.fr
    steps:

    - name: Get project name
      run: |
        echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

    - name: Use autodevops to deploy production
      uses: SocialGouv/actions/autodevops@autodevops-app
      with:
        environment: prod
        project: ${{ env.project }}
        token: ${{ secrets.GITHUB_TOKEN }}
        imageName: ozensemble/ozensemble-site
        kubeconfig: ${{ secrets.SOCIALGOUV_KUBE_CONFIG_PROD }}
